# Generated by Django 4.0.2 on 2022-02-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_name', models.CharField(max_length=30)),
                ('E_Email', models.EmailField(max_length=254)),
                ('E_city', models.CharField(max_length=20)),
                ('E_mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
