# Generated by Django 4.0.2 on 2022-03-03 06:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('number', models.BooleanField(default=True, primary_key=api.models.Theaters, serialize=False)),
            ],
        ),
    ]
