# Generated by Django 4.0.2 on 2022-03-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
