# Generated by Django 4.0.2 on 2022-03-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='Date',
        ),
    ]
